version: '3.8'
services:
  payment-service:
    depends_on:
      - mongodb
    image: payment-service-app:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:aaa123@mongodb:27017/paymentdb?authSource=admin"
      SPRING_DATA_MONGODB_AUTHENTICATING_DATABASE: "admin"
  booking-service:
    depends_on:
      - mongodb
    image: booking-service-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:aaa123@mongodb:27017/bookingdb?authSource=admin"
      SPRING_DATA_MONGODB_AUTHENTICATING_DATABASE: "admin"
  mongodb:
    image: mongo:7.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: aaa123
      MONGO_INITDB_DATABASE: paymentdb
    ports:
      - "27017:27017"
