version: '3.8'
services:
  payment-service:
    depends_on:
      - mongodb
    image: payment-service-app:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:aaa123@mongodb:27017/paymentdb?authSource=admin"
      SPRING_DATA_MONGODB_AUTHENTICATING_DATABASE: "admin"

  booking-service:
    depends_on:
      - mongodb
      - payment-service
    image: booking-service-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:aaa123@mongodb:27017/bookingdb?authSource=admin"
      SPRING_DATA_MONGODB_AUTHENTICATING_DATABASE: "admin"
      PAYMENT_SERVICE_BASE_URL: "http://payment-service:8081"

  mongodb:
    image: mongo:7.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: aaa123
      MONGO_INITDB_DATABASE: paymentdb
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
